### ISSUE TITLE
peakHeatmap / plotAvgProf2

### ISSUE THREAD

**Issue by jerryhuang01** [GuangchuangYu/ChIPseeker#1]
Hi, Guangchuang:

Thanks again for the great work. Some minor issues regarding the peakHeatmap / plotAvgProf2 commands:

While passing the GRanges object "peakAnno" (from annotatePeak) to peakHeatmap / plotAvgProf2 commands, the following error is returned:

> > preparing promoter regions...         2014-12-03 02:43:15 PM 
> > preparing tag matrix...               2014-12-03 02:43:16 PM 
> > Error in file.exists(peak) : invalid 'file' argument
> > Calls: peakHeatmap -> getTagMatrix -> loadPeak -> file.exists
> > Execution halted

The same GRanges object works well with other commands plotAnnoPie / plotAnnoBar / plotDistToTSS.

Thanks a million.

ChIPseeker: 1.2.0
Bicoconductor 3.0
R 3.1.1

**Comment by benxiahu** [comment]
when  I  run ChIPseeker ，but  I met  the  error:Error in file.exists(peak) : invalid 'file' argument.
I  really  don`t  know  why

**Comment by GuangchuangYu** [comment]
You should present more information here and please don't send duplicate msg via email.

Please read the man page of the function.

As I replied by email, covplot only accept GRanges object or bed file name.

In your case, only
```r
covplot("H3K4me3-HE_vs_WT_peaks.bed", weightCol="V5") 
```
or
```r
peakH3K4<-readPeakFile("H3K4me3-HE_vs_WT_peaks.bed")
covplot(peakH3K4, weightCol="V5")
```
will works.
