### ISSUE TITLE
Error when using new parameter distanceToTSS_cutoff in  enrichAnnoOverlap

### ISSUE THREAD

**Issue by riederd** [GuangchuangYu/ChIPseeker#10]
enrichAnnoOverlap(myPeaks, GEOpeaks, TxDb = txdb, pAdjustMethod = "BH", distanceToTSS_cutoff = 10000)

produces:
Error in `colnames<-`(`*tmp*`, value = c("Feature", "Frequency")) : 
  'names' attribute [2] must be the same length as the vector [1]

**Comment by GuangchuangYu** [comment]
and it has been [fixed](https://github.com/GuangchuangYu/ChIPseeker/commit/942d8155b73a3230e6d55994d3e104c881473aa1).
