### ISSUE TITLE
question about annotation

### ISSUE THREAD

**Issue by februaryfang** [GuangchuangYu/ChIPseeker#12]
hello GuangchuangYu,
     ChIPseeker was really help me a lot.
     Now, I have a question about the annotation result.I print the result after annotatePeak,the detail information are as follows: 

seqnames	start	end	width	strand	annotation	geneChr	geneStart	geneEnd	geneLength	geneStrand	geneId	transcriptId	distanceToTSS
1	3178055	3179048	994	*	Intron (ENST00000511072/ENSG00000142611, intron 3 of 15)	1	3160696	3303482	142787	+	ENSG00000142611	ENST00000463591	18352
1	7019270	7020286	1017	*	Intron (ENST00000303635/ENSG00000171735, intron 3 of 22)	1	7068436	7074339	5904	-	ENSG00000237365	ENST00000456701	55069
1	7507693	7508565	873	*	Intron (ENST00000303635/ENSG00000171735, intron 5 of 22)	1	7501156	7501614	459	-	ENSG00000225126	ENST00000440032	-6951
1	10010122	10011152	1031	*	Intron (ENST00000403197/ENSG00000173614, intron 1 of 4)	1	10007376	10007694	319 ENSG00000202415	ENST00000365545	3776
1       145555716       145558806       3091    *       Exon (ENST00000355594/ENSG00000198483, exon 2 of 14)    1       145549244       145561166       11923   +       ENSG00000198483 ENST00000544626 9562

In the above results we can find that the 'annotation' column not only given the location information, but also provides a specific explanation.But the geneId and transcriptId	from the ‘annotation’ column  are not consistent with the following column named 'geneId' and 'transcriptId'.At this situation,how can I understand the meaning of 'annotation' column,especially the description of the brackets.

thanks for your help.

**Comment by GuangchuangYu** [comment]
those columns start with **gene** are information of nearest gene while annotation is genomic feature of where is peak is located. see also [https://github.com/GuangchuangYu/ChIPseeker/issues/2](https://github.com/GuangchuangYu/ChIPseeker/issues/2).

**Comment by GuangchuangYu** [comment]
see also [http://ygc.name/2014/10/01/multiple-annotation-in-chipseeker/](http://ygc.name/2014/10/01/multiple-annotation-in-chipseeker/)
