### ISSUE TITLE
question about ‘annotatePeak’

### ISSUE THREAD

**Issue by februaryfang** [GuangchuangYu/ChIPseeker#14]
hi GCY,

I have two questions.As follows:
1.I had read Instruction manual about ‘annotatePeak’, the parameter 'tssRegion' is set to "c(-3000, 3000)". And 'tssRegion' is means "Region Range of TSS".Now I only hope peaks are annotate to promoter's upstream 2000bp and downstream 2000bp.I changed the parameter 'tssRegion' ,but I failed.The 'annotation' coloum in result file also including "Promoter (<=1kb)、Promoter (1-2kb)、Promoter (2-3kb)".
2.Genomic features of the peak in result have 11 categories.How should I understand ‘downstream’? I try to think it is means as downstream of a gene.But how you classify downstream to 3 categories?

Thank you for your help.
FF

**Comment by GuangchuangYu** [comment]
The first issue is an old issue that had been fixed, see the example below:

```r
> require(ChIPseeker)
Loading required package: ChIPseeker
> ff=getSampleFiles()
> x=annotatePeak(ff[[1]], tssRegion=c(-2000, 2000))
>> loading peak file...				 2015-10-09 17:43:16
>> preparing features information...		 2015-10-09 17:43:16
>> identifying nearest features...		 2015-10-09 17:43:18
>> calculating distance from peak to TSS...	 2015-10-09 17:43:18
>> assigning genomic annotation...		 2015-10-09 17:43:18
>> assigning chromosome lengths			 2015-10-09 17:43:42
>> done...					 2015-10-09 17:43:42
> x
Annotated peaks generated by ChIPseeker
807/812  peaks were annotated
Genomic Annotation Summary:
             Feature  Frequency
8   Promoter (<=1kb)  2.1065675
9   Promoter (1-2kb)  3.0978934
3             3' UTR  0.6195787
1           1st Exon  0.2478315
6         Other Exon  2.1065675
2         1st Intron  7.1871128
7       Other Intron 33.3333333
5 Downstream (<=3kb)  0.3717472
4  Distal Intergenic 50.9293680
```

You need to update your `ChIPseeker` installation.

For 2nd issue, please refer to [the vignette](http://www.bioconductor.org/packages/3.2/bioc/vignettes/ChIPseeker/inst/doc/ChIPseeker.html#peak-annotation).

**Comment by MaryamLabaf** [comment]
Hi,
This question has been asked before. How can we classify the downstream to 3 categories for annotatePeak.
I looked up the vignette and still not being able to modify the TxDb to the format I need. Would you please let me know how can I resolve this problem? 
Thank you.
Mary
