### ISSUE TITLE
extend getPromoters()

### ISSUE THREAD

**Issue by GuangchuangYu** [GuangchuangYu/ChIPseeker#16]
`getPromoters()` function prepare a `GRanges` object of promoter regions by user specify upstream and downstream distance from Transcript Start Site (TSS).

Refer to the questions in Bioconductor support site: [https://support.bioconductor.org/p/73069/#73157](https://support.bioconductor.org/p/73069/#73157) and [https://support.bioconductor.org/p/73377/](https://support.bioconductor.org/p/73377/), some users (studying RNA splicing I guess) may interesting in how protein binding to the start of intron/exon. 

`getPromoters()` function will extend to support output a `GRanges` object of Intron/Exon start region similar to Transcript start region.

Maybe the function name should be changed.

**Comment by GuangchuangYu** [comment]
@Puriney do you have any recommendation of the new function name? or we just use the `getPromoters()` for all types?

**Comment by Puriney** [comment]
```R
getBioRegion(..., by = c('gene', 'transcript', 'promoter', 'exon','intron'))
```

**Comment by GuangchuangYu** [comment]
[https://github.com/GuangchuangYu/ChIPseeker/commit/5bc25bb7bcb65fe9b779dd890e459023e50fb45f](https://github.com/GuangchuangYu/ChIPseeker/commit/5bc25bb7bcb65fe9b779dd890e459023e50fb45f)
