### ISSUE TITLE
annotatePeak issue with overlapping genes 

### ISSUE THREAD

**Issue by karlmzhang** [GuangchuangYu/ChIPseeker#2]
Hi, Dear Prof. Yu.

I was trying to use your package in my collaborative research, and I really like the general setup of the package.

However, I may have found a bug in annotatePeak function. One example where the bug may lead t o some scientific problems is as follows.

Let A and B be two genes that overlaps with each other in genomic locations, 
and P be a peak in an exon/intron of A but not in the gene body of B.
If the TSS of B is closer to P, annotatePeak will output some of the gene information of B instead of A, yet the annotation column will still show that it is in the exon/intron of A.

One example of such genes are Xkr4 and AK149000 on mm9.

This may cause problem if one wants to use the output gene information to do gene set enrichment analysis.

I think the problem is that the output gene information retrieved from the output of getNearestFeatureIndicesAndDistances, which only consider distance to TSS but not the actual overlaps with the gene body, while the annotation of exon/intron is from the actual overlaps between peaks and features. 

I have been trying to fix this since yesterday, and my current strategy is to let getGenomicAnnotation also output gene ID of the actual annotation, and use the gene ID to retrieve the gene information and re-calculate distance to TSS afterwards.

I figured out that you may have a better solution, but I will also post my solution once I have a working version.Thanks.

Qi Zhang

**Comment by karlmzhang** [comment]
I should have said that the issue happens more often when level='transcript', and Xkr4 and AK149000 are regarded as two transcripts of gene Xkr4 by pakcages TxDb.Mmusculus.UCSC.mm9.knownGene and/or org.Mm.eg.db

**Comment by GuangchuangYu** [comment]
This is not a bug. There are two kind of annotation, one is looking for closest TSS (in your example, B), and the other one is annotating where the peak is located.

There are two separate annotations.
