### ISSUE TITLE
Adding '.id' to list of annotated peak files

### ISSUE THREAD

**Issue by norapeterson** [GuangchuangYu/ChIPseeker#21]
Hi,
I am hoping to use a list of annotated peak files to make visual comparisons between treatments. I followed the guide using my own data. However, I have run into an id issue when I try to annotate a list of files. Is there anyway to add ids (perhaps in the initial "myFiles" list) to the peak files so that I can use ChIPseeker's comparison plots? 

Sincerely,
Nora Peterson

> myFiles <- list.files(pattern="*.txt")
> peakAnnoList <- lapply(myFiles, annotatePeak, TxDb=txdb,
                              tssRegion=c(-3000, 3000), verbose=FALSE)
> peakAnnoList
[[1]]
Annotated peaks generated by ChIPseeker
16319/16359  peaks were annotated
Genomic Annotation Summary:
              Feature  Frequency
9    Promoter (1-2kb)  1.5319566
10   Promoter (<=1kb) 70.9602304
11   Promoter (2-3kb)  1.3358662
4              5' UTR  0.4595870
3              3' UTR  0.8517679
1            1st Exon  0.7353392
7          Other Exon  1.4645505
2          1st Intron  1.7893253
8        Other Intron  4.9451560
6  Downstream (<=3kb)  0.4963539
5   Distal Intergenic 15.4298670
[[2]]
Annotated peaks generated by ChIPseeker
16845/16890  peaks were annotated
Genomic Annotation Summary:
              Feature  Frequency
9    Promoter (1-2kb)  1.6859602
10   Promoter (<=1kb) 69.2668448
11   Promoter (2-3kb)  1.3831998
4              5' UTR  0.4689819
3              3' UTR  0.9260908
1            1st Exon  0.8489166
7          Other Exon  1.5197388
2          1st Intron  2.0124666
8        Other Intron  5.4615613
6  Downstream (<=3kb)  0.4867913
5   Distal Intergenic 15.9394479

etc. etc. through 8 files

> plotAnnoBar(peakAnnoList)
Error in eval(expr, envir, enclos) : object '.id' not found

**Comment by GuangchuangYu** [comment]
```r
myFiles <- list.files(pattern="*.txt")
### should have name attribute, which was used to label the bar
names(myFiles) <- myFiles
###

peakAnnoList <- lapply(myFiles, annotatePeak, TxDb=txdb,
tssRegion=c(-3000, 3000), verbose=FALSE)
peakAnnoList
plotAnnoBar(peakAnnoList)
```
