### ISSUE TITLE
details of annotating ChIP-seq peaks 

### ISSUE THREAD

**Issue by crazyhottommy** [GuangchuangYu/ChIPseeker#22]
Hi Guangchuan,

I am looking into the details of how `annotatePeak` work and found it internally uses this function:
[`getNearestFeatureIndicesAndDistances`](https://github.com/GuangchuangYu/ChIPseeker/blob/master/R/getNearestFeatureIndicesAndDistances.R)

I saw

```{r}
    ## nearest from peak start
    ps.idx <- precede(peaks, features)
    
    ## nearest from peak end
    pe.idx <- follow(peaks, features)

```

I understand for ChIP-seq peaks, there is no strandness.

precede will actually return nearest from peak end.
follow will actually return nearest from peak start.

See some of my testing here http://crazyhottommy.blogspot.com/2016/01/find-nearest-upstream-genes-using.html

**Comment by GuangchuangYu** [comment]
This is indeed a bug and it was fixed in ChIPseeker (version >=1.7.5)
