### ISSUE TITLE
covplot help

### ISSUE THREAD

**Issue by gonzalpk** [GuangchuangYu/ChIPseeker#27]
I am interested in creating color overlays using two covplot outputs (peaks from H3KK9me3 and H3K27me3). This is quite easy to do in photoshop when both covplot outputs are the same size (attached screenshot), but quite difficult if they are not. Is there a way to keep the covplot scaling the same regardless of the number of peaks that are present in the input file? I only run into the problem when I have a file with few (~100) differentially called peaks. I should mention I am only interested in the location (not size) of the peak, so my input file only consist of chromosome, start, and end columns. 
Thank you for your time.
 
![overlayexample]
(https://cloud.githubusercontent.com/assets/7812125/13183344/b9968b18-d6f3-11e5-965d-83e1bd47b6a1.png)

**Comment by GuangchuangYu** [comment]
try using [xlim](http://www.inside-r.org/packages/cran/ggplot2/docs/xlim).

**Comment by GuangchuangYu** [comment]
see my solution in http://guangchuangyu.github.io/2016/02/covplot-supports-grangeslist/

**Comment by gonzalpk** [comment]
Thank you. This is excellent.

**Comment by gonzalpk** [comment]
Is the covplot modification already in the bioconductor package? I have tried to run the command on your test data and get the following error message.


> library(ChIPseeker)

> files=getSampleFiles()

> peak=GenomicRanges::GRangesList(CBX6=readPeakFile(files[[4]]), CBX7=readPeakFile(files[[5]]))

> p=covplot(peak)

Error in file.exists(peak) : invalid 'file' argument


Patrick Gonzales
Link lab, Department of Integrative Physiology
University of Colorado, Boulder



________________________________

**Comment by GuangchuangYu** [comment]
new features only go to the devel branch. The current devel branch will be release at April when new version of R was released.

**Comment by eryildiz** [comment]
Is there a way to adjust the y-axis scale to make the peak heights comparable at one specific region between two samples?
