### ISSUE TITLE
[New] Add CI by bootstrapping

### ISSUE THREAD

**Issue by Puriney** [GuangchuangYu/ChIPseeker#3]
Confidence interval of the TSS coverage plot is probably one of the features that users need. I have implemented it by using bootstrapping via third-party package `boot`. See my fork: https://github.com/Puriney/ChIPseeker

**Demo**

```
plotAvgProf(tagMatrix, xlim = c(-3000, 3000), conf = 0.95)
```

My implementation is elegant for both users and you. Hopefully you will agree with me that I did not mess up your source codes. 
**Note**
Currently CI feature can only support single one `tagMatrix` data. It cannot handle if user feeds it with a list of data. I am happy to implement it further but the reason why I hesitate is that the final figure will be messed if many data is plotted simultaneously. For example in your own plot [here](http://ygc.name/2014/04/30/visualization-methods-in-chipseeker/avgprof2/). If there were 10 proteins in the same one figure, I'm afraid that the science story behind figure becomes less straightforward, let alone with CI being added. 

To address the problem, I am thinking of multiple plots in one page. But whether I will go in this way depends on whether we are ok with current design. More importantly, after all you are the author and this is my 1st time being here, so I will leave it later. 

Anyway, I will make CI estimation compatible with multiple inputs of tagMatrix, hopefully in short time.

**Comment by GuangchuangYu** [comment]
I like this feature and of course multiple plots in one page is a good design for tagMatrixList.

I would like to add you as a contributor in author list (see https://github.com/GuangchuangYu/clusterProfiler/blob/master/DESCRIPTION), please give me your information.

**Comment by GuangchuangYu** [comment]
already added, https://github.com/GuangchuangYu/ChIPseeker/blob/master/DESCRIPTION
