### ISSUE TITLE
wrong annotation with annotatePeak

### ISSUE THREAD

**Issue by spooner1** [GuangchuangYu/ChIPseeker#31]
Hi,

I have two peaks (hg19):

chr1,19234321,19235388
chr1,40241808,40243451

The first one is annotated to ALDH4A1, which has the closest TSS, with a distance of -5028 bp to the TSS. With default settings, in column 'annotation' I would expect 'Distal Intergenic', but it is '3'UTR'. Keeping a look in the UCSC GenomeBrowser, it is clear why: ALDH4A1 has the closest TSS, but the peak overlaps with the 3'UTR of the next gene, which is IFFO2.
The second Peak is annotated to OXCT2, which is again the closest TSS. The distance to the TSS is -4788 bp, which should again be annotated as 'Distal Intergenic', but it is annotated to the 6th Intron of BMP8B. I think it is the same issue as with the first peak, but with another mistake: BMP8B is on the reverse strand, it is the first Intron, not the 6th.
I also tried to change genomicAnnotationPriority to prefer 'Intergenic' before 'Promoter', with no effect. I think both cases are not the expected behaviour. I used ChIPseeker-version 1.6.7

Best Regards

**Comment by GuangchuangYu** [comment]
see <https://github.com/GuangchuangYu/ChIPseeker/issues/2>, <https://github.com/GuangchuangYu/ChIPseeker/issues/12> and <http://guangchuangyu.github.io/2014/10/multiple-annotation-in-chipseeker/>
