### ISSUE TITLE
update to a newer version

### ISSUE THREAD

**Issue by februaryfang** [GuangchuangYu/ChIPseeker#35]
hello ,GuangchuangYu
     My ChIPseeker version is 1.5.11 now. I just want to update the version to 1.7.15 ,because my R environment can't support the lastest version(1.9.0). So, How can I install it on linux from the number 142 commit(https://codeload.github.com/Bioconductor-mirror/ChIPseeker/zip/f6ed99c7c95157a5bad32b0336078ec587b226bd) ?

FF

**Comment by GuangchuangYu** [comment]
You should upgrade your R to 3.3.0 and install ChIPseeker 1.8.3, follow the guide in <http://bioconductor.org/packages/release/bioc/html/ChIPseeker.html>
