### ISSUE TITLE
Error in enrichPeakOverlap

### ISSUE THREAD

**Issue by cattapre** [GuangchuangYu/ChIPseeker#36]
I have been following the vignette with my own data, but cannot run enrichPeakOverlap. I got a message as below. 
```
> enrichPeakOverlap(queryPeak     = files[[6]], 
+                   targetPeak    = unlist(files[1:5]), 
+                   TxDb          = txdb, 
+                   pAdjustMethod = "BH", 
+                   nShuffle      = 50, 
+                   chainFile     = NULL,
+                   mc.cores      = detectCores() - 1,
+                   verbose       = FALSE)
Error in file.exists(dir) : invalid 'file' argument
```
I tried to run with the supplied datafile, but got an error, too. What can it be the issue? Thanks!

**Comment by GuangchuangYu** [comment]
make sure you are using the [latest release version](https://guangchuangyu.github.io/2016/07/how-to-bug-author).

**Comment by cattapre** [comment]
Dear GuangchuangYu,

I keep it updated it; last time was a couple of days ago. Any clues?

Thanks

Rinaldo Catta-Preta


Sent from my Windows Phone
________________________________

**Comment by GuangchuangYu** [comment]
checkout:
```r
print(unlist(files[1:5]))
print(length(unlist(files[1:5])))
```

**Comment by cattapre** [comment]
I got them. Please see attachment
[output.txt](https://github.com/GuangchuangYu/ChIPseeker/files/372363/output.txt)

**Comment by GuangchuangYu** [comment]
You don't need to install devel branch. You only need to install devel branch if there are features you needed is not available in release branch.

I found the issue from your output. Your input `unlist(files)[1:5]` is actually a list of `GRanges` object, and `ChIPseeker` test whether the input is `GRanges` by `is(targetPeak[1], "GRanges")`.

I fixed it by using `is(targetPeak[1], "GRanges") || is(targetPeak[[1]], "GRanges")`, see <https://github.com/GuangchuangYu/ChIPseeker/commit/0fc0fed9a47b9fbaaacd156d58c73ade8b500e45>.

You may need to wait several days (2-3 expected) for Bioconductor to update the tarball, and then you can use `biocLite('ChIPseeker')` to install the updated verstion (1.8.7).

**Comment by cattapre** [comment]
Thanks!

**Comment by cattapre** [comment]
Guangchuang, I updated ChIPseeker to 1.8.7, but still not working. Below is the error I get (same files)
> enrichPeakOverlap(queryPeak     = files[[6]], 
+                   targetPeak    = unlist(files[1:5]), 
+                   TxDb          = txdb, 
+                   pAdjustMethod = "BH", 
+                   nShuffle      = 50, 
+                   chainFile     = NULL,
+                   mc.cores      = detectCores() - 1,
+                   verbose       = FALSE)
Error in sub(".+/", "", targetFiles) : object 'targetFiles' not found
