### ISSUE TITLE
New Error in enrichPeakOverlap

### ISSUE THREAD

**Issue by cattapre** [GuangchuangYu/ChIPseeker#37]
Guangchuang, I updated ChIPseeker to 1.8.7, but still not working. Below is the error I get (same files)

enrichPeakOverlap(queryPeak = files[[6]], 
• targetPeak = unlist(files[1:5]), 
• TxDb = txdb, 
• pAdjustMethod = "BH", 
• nShuffle = 50, 
• chainFile = NULL,
• mc.cores = detectCores() - 1,
• verbose = FALSE)

Error in sub(".+/", "", targetFiles) : object 'targetFiles' not found

**Comment by GuangchuangYu** [comment]
pls follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/) and send me a reproducible example with source code.

**Comment by cattapre** [comment]
Sorry for the lack of continuity. As per Issue #36, I had been following the vignette with my own data, but cannot run enrichPeakOverlap. I got a message as below.

> enrichPeakOverlap(queryPeak     = files[[6]], 
+                   targetPeak    = unlist(files[1:5]), 
+                   TxDb          = txdb, 
+                   pAdjustMethod = "BH", 
+                   nShuffle      = 50, 
+                   chainFile     = NULL,
+                   mc.cores      = detectCores() - 1,
+                   verbose       = FALSE)
Error in file.exists(dir) : invalid 'file' argument

I tried to run with the supplied datafile, but got an error, too. You asked me to provide you with  theprint(unlist(files[1:5])) and print(length(unlist(files[1:5]))) for them, which are on the attached output.txt file
[output.txt](https://github.com/GuangchuangYu/ChIPseeker/files/381856/output.txt)
You made some corrections to the module, and asked me to update it to version 1.8.7, which I did. All packages are updated.
However, when I run the same data files through enrichPeakOverlap I got the following error:
> # Peak overlap enrichment analysis
> enrichPeakOverlap(queryPeak     = files[[6]], 
+                   targetPeak    = unlist(files[1:5]), 
+                   TxDb          = txdb, 
+                   pAdjustMethod = "BH", 
+                   nShuffle      = 50, 
+                   chainFile     = NULL,
+                   mc.cores      = detectCores() - 1,
+                   verbose       = FALSE)
Error in sub(".+/", "", targetFiles) : object 'targetFiles' not found

Could you please help? Thanks

**Comment by GuangchuangYu** [comment]
As I said, you need to make an example to reproduce your issue. That means I can run on my computer and produce exactly the same error.

**Comment by cattapre** [comment]
Pls find attached the code and the files
[ChIPseeker_test.tar.gz](https://github.com/GuangchuangYu/ChIPseeker/files/382185/ChIPseeker_test.tar.gz)

**Comment by GuangchuangYu** [comment]
your script is just too long with many commands that are not related to this issue. 

I recommend you to read <https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example>.

Specific to your case, all you need is:

```r
## Load libraries
library(ChIPseeker)
library(TxDb.Mmusculus.UCSC.mm9.knownGene)

# Load reference genome
txdb <- TxDb.Mmusculus.UCSC.mm9.knownGene

filelist <- read.table("dirlist.txt", header = FALSE)
filenames <- read.table("dirlist.txt", header = FALSE, sep = "_")

filenames[,ncol(filenames)+1] <- paste(filenames[,1], "_", filenames[,2], sep = "")

filenames <- as.vector(filenames[,ncol(filenames)])
filelist <- as.vector(filelist[1:nrow(filelist), 1])

namedlist <- c()

for (i in 1:length(filenames)) {
  name <- filenames[i];
  namedlist[[name]] <- filelist[i]
}


files <- lapply(namedlist, readPeakFile, as = "GRanges", header = FALSE)

# Peak overlap enrichment analysis
enrichPeakOverlap(queryPeak     = files[[6]], 
                  targetPeak    = unlist(files[1:5]), 
                  TxDb          = txdb, 
                  pAdjustMethod = "BH", 
                  nShuffle      = 50, 
                  chainFile     = NULL,
                  mc.cores      = detectCores() - 1,
                  verbose       = FALSE)
```

`enrichPeakOverlap` expect targetPeak to be `bed` files and the error was due to it try to get the basename by removing file path.


Currently, you can use:
```r

enrichPeakOverlap(queryPeak     = namedlist[[6]], 
                  targetPeak    = unlist(namedlist[1:5]), 
                  TxDb          = txdb, 
                  pAdjustMethod = "BH", 
                  nShuffle      = 50, 
                  chainFile     = NULL,
                  mc.cores      = detectCores() - 1,
                  verbose       = FALSE)
```

or waiting 2-3 days for Bioconductor to update the tarball and install ChIPseeker >=1.8.8, which fixed the issue.

**Comment by GuangchuangYu** [comment]
just figure out that you can use `devtools:::install_bioc("release/ChIPseeker")` to install `ChIPseeker` from BioC svn repo. No need to wait update from Bioconductor website.

**Comment by cattapre** [comment]
Thanks, GuangchuangYu. It is working now.
