### ISSUE TITLE
question about strand

### ISSUE THREAD

**Issue by rojasp** [GuangchuangYu/ChIPseeker#49]
Hi, 
I have a question about the strand (+/-) given after peak annotation. Regarding the strand given for each chr. coordinate, I want to select a specific window of the gene (-50 bp to 200 bp around geneStart).So, for example If I have the follow annotation

geneStart  geneEnd  strand 
20156        23456      1
23584        46953      2

I've just wondering if I make sure that I'm subtracting and adding bp in the appropriate direction, or it could be : geneStart -50   geneStart + 200 in both cases (strand - and +)

Thank you very much in advance,

Best,

**Comment by GuangchuangYu** [comment]
the *geneEnd* is actually geneStart if it is on - strand.
​

**Comment by rojasp** [comment]
So ti shift the region it should be:
geneStart-50 geneStart+200  (strand +)
geneEnd-50   geneEnd+200 (strand -)

Is this correct?

Thank!

**Comment by GuangchuangYu** [comment]
```
geneEnd+50 geneEnd-200 (strand -)
```

**Comment by rojasp** [comment]
Just to be clear for me, Is this correct? 

original data
geneStart geneEnd strand
20156    23456 1
23584   46953 2

Shift data
geneStart         geneEnd    strand
(20156-50)        (20156+200)   +
( 46953+50)       ( 46953 -200)    -

**Comment by GuangchuangYu** [comment]
yes.
