### ISSUE TITLE
Error in downloading GEO data with the  function "downloadGEObedFiles"

### ISSUE THREAD

**Issue by xiatingp** [GuangchuangYu/ChIPseeker#52]
Hello,there
I am getting an annoying error while trying to download GEO data with chipseeker. I tried something like below:

require(ChIPseeker)
getGEOgenomeVersion()
hg19 <- getGEOInfo(genome="hg19", simplify=TRUE)
downloadGEObedFiles(genome="hg19", destDir="hg19")
gsm <- hg19$gsm[sample(nrow(hg19), 10)]
downloadGSMbedFiles(gsm, destDir="hg19")

and it gives me the following error:
Error in download.file(fnames[i], destfile = destfiles[i], mode = "wb") : 
  cannot open destfile 'hg19/GSM521889_UCSD.IMR90.H3K27me3.SK05.bed.gz', reason 'No such file or directory'

or:
Error in download.file(fnames[i], destfile = destfiles[i], mode = "wb") : 
  cannot open destfile 'hg19/GSM521933_UCSD.IMR90.Input.SK-I3.bed.gz', reason 'No such file or directory'

Can you please help me what is wrong here?

**Comment by GuangchuangYu** [comment]
You did not create the folder `hg19` before ` downloadGEObedFiles(genome="hg19", destDir="hg19")`.

The error `'No such file or directory'` already tell you everything.

**Comment by xiatingp** [comment]
That's it! Thanks a lot!
