### ISSUE TITLE
Annotation of peaks that overlap multiple genes/TSS?

### ISSUE THREAD

**Issue by romanhaa** [GuangchuangYu/ChIPseeker#55]
I really like this tool for multiple reasons, including nice visualisation. However, one thing that I need to know in order to be fully convinced, is how peaks are annotated that overlap multiple genes and/or TSS.

Let me take chr3:137,806,020-137,806,847 as an example. The region is only 800 bp long, yet it contains TSS regions for 2 genes: Mttp and Rg9mtd2. In my personal experiment (where the region is slightly larger but anyway covers both TSS), it is annotated as Mttp, but based on the shape of the peak it seems it actually tends to lean into the Rg9mtd2 gene body.

What is the rule during the annotation? Is it the based on the size of the overlap with the two genes (annotating the gene with larger overlap), or maybe it takes the first entry in the annoDb that matches? I think the best (and quite easy) solution would be to report both genes.

I would greatly appreciate a response because we can't use the results for a publication if we don't fully understand the annotation.

Thanks!

**Comment by GuangchuangYu** [comment]
ChIPseeker just report the first entry in TxDb.

**Comment by romanhaa** [comment]
Would it be a lot of work to change this so that it reports all matching genes? Or could you point me to the file so that I can branch and adapt it myself?

**Comment by GuangchuangYu** [comment]
`addFlankGeneInfo` parameter (see example in <http://guangchuangyu.github.io/2014/10/multiple-annotation-in-chipseeker/>) maybe useful.

**Comment by romanhaa** [comment]
Thanks, that actually looks quite promising!
