### ISSUE TITLE
annotate peak Intron annotation error when using chicken GFF

### ISSUE THREAD

**Issue by abrionne** [GuangchuangYu/ChIPseeker#57]
Hi,

I recieve an error from **annotatePeak** caused by **Intron** in genomicAnnotationPriority, when I want annotate txdb object from chicken.
So, I tried to understand where the error came from:

1. ChIPseeker version: **ok**

`rvcheck::check_bioc("ChIPseeker")`

> package is up-to-date release version
> $package
> [1] "ChIPseeker"
> 
> $installed_version
> [1] "1.12.0"
> 
> $latest_version
> [1] "1.12.0"
> 
> $up_to_date
> [1] TR

2. Build a txdb database from chicken GFF: **ok**

`
 txdb<-GenomicFeatures::makeTxDbFromGFF("ftp://ftp.ncbi.nlm.nih.gov/genomes/Gallus_gallus/GFF/ref_Gallus_gallus-5.0_top_level.gff3.gz",organism="Gallus gallus",taxonomyId=9031)`

3. write an example.bed file with this genomic location:
```
chr	start	end	FDR	fct	strand
 NC_006088.4	143600	145799	6.7819865603e-18	127.207954544
```
4. read it with readPeakFile: **ok**

` peak<-ChIPseeker::readPeakFile("example.bed",header=T)`

5. annotate peaks: **error**

`peakAnno<- ChIPseeker::annotatePeak(peak, TxDb=txdb)  `

> Error in `[[<-`(`*tmp*`, name, value = c(1L, 2L, 3L, 4L, 5L, 1L, 1L, 2L,  : 
>  639501 elements in value to replace 639591 elements

6. annotate peaks **without Intron** argument in genomicAnnotationPriority : **ok**

` peakAnno<- ChIPseeker::annotatePeak(
     peak,
    TxDb=txdb,
    genomicAnnotationPriority = c("Promoter", "5UTR", "3UTR", "Exon","Downstream", "Intergenic")
)  `

7. annotate peaks **Intron** bug location: **ok**

The bug seems to come from your **getGenomicAnnotation.internal** function for type=="Intron".

I locate the error at this step,  but I don't understand the problem... and how to solve it.

>         GRegion$intron_rank <- lapply(seq_along(strd), function(i) {
>             rank <- seq(1, len[i])
>             if (strd[i] == '-')
>                 rank <- rev(rank)
>             return(rank)
>         }) %>% unlist
>     }

I have also an another species (quail) with **annotatePeak**, and it work perfectly.

Any suggestion,

Sincerely,

Aurélien

**Comment by GuangchuangYu** [comment]
pls follow the guideline, <https://github.com/GuangchuangYu/ChIPseeker/issues/new>, for reporting issue.

**Comment by balwierz** [comment]
Thank you abrionne, you saved my afternoon.

**Comment by GuangchuangYu** [comment]
if you guys can provide a reproducible example, I can help figuring out what's going on here. 

It seems quite prokaryotic specific problem.

**Comment by abrionne** [comment]
Hi GuangchuangYu and balwierz,

I update my initial comment 'see above', in order to provide a full reproducible example for **chicken**.
I think  that the problem come from several chromosome location assignment to a single GeneID,  but I am **really not sure** about this.

**Comment by GuangchuangYu** [comment]
thanks for the example. It was fixed.

You can wait 2-3 days for bioconductor to update the release version or install the github version.

**Comment by abrionne** [comment]
Thank you very much Yu , for this quick correction.
Your package save a lot of time for my data analysis.

Sincerley,

Aurélien,
