### ISSUE TITLE
I use the latest release version of Chipseeker

### ISSUE THREAD

**Issue by sunxuwu** [GuangchuangYu/ChIPseeker#67]
### Prerequisites

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/chipseeker/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [x] make sure your are using the latest release version
	* [ ] read the [documents](https://guangchuangyu.github.io/chipseeker/documentation/)
	* [ ] google your quesion/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `ChIPseeker`

**Comment by sunxuwu** [comment]
library(ChIPseeker)
library(TxDb.Athaliana.BioMart.plantsmart22)
txdb <- TxDb.Athaliana.BioMart.plantsmart22
library(clusterProfiler)
files <- getSampleFiles()
print(files)
peak <- readPeakFile(files[[5]])
peak
covplot(peak, weightCol="V4")
covplot(peak, weightCol="V4", chrs=c("2", "3"), xlim=c(4.5e6, 5e6))promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000, by = "gene")
tagMatrix <- getTagMatrix(peak, windows=promoter)
tagMatrix <- getTagMatrix(peak, weightCol = NULL,windows = promoter)
tagMatrixList <- lapply(files, getTagMatrix, windows=promoter)
tagMatrix <- tagMatrixList[[5]]
tagHeatmap(tagMatrix, xlim=c(-3000, 3000), color="red")
peakHeatmap(files[[5]], TxDb=txdb, upstream=3000, downstream=3000, color="red")
plotAvgProf(tagMatrix, xlim=c(-3000, 3000),
            xlab="Genomic Region (5'->3')", ylab = "Read Count Frequency")
plotAvgProf2(files[[5]], TxDb=txdb, upstream=3000, downstream=3000,
             xlab="Genomic Region (5'->3')", ylab = "Read Count Frequency")
plotAvgProf(tagMatrix, xlim=c(-3000, 3000), conf = 0.95, resample = 3000)
library(org.At.tair.db)
peakAnno <- annotatePeak(files[[5]], tssRegion=c(-3000, 3000),
                         TxDb=txdb, annoDb="org.At.tair.db")


I use library(org.At.tair.db)for peak annotate, but doesn't work

would you please suggest me a right annotation library for Arabidopsis?

**Comment by GuangchuangYu** [comment]
```
files <- getSampleFiles()
print(files)
peak <- readPeakFile(files[[5]])
``` 

why you expect to annotate the `peak` (from hg19) using Arabidopsis TxDb to be succeed?

**Comment by sunxuwu** [comment]
## loading packages
library(ChIPseeker)
library(TxDb.Athaliana.BioMart.plantsmart22)
txdb <- TxDb.Athaliana.BioMart.plantsmart22
library(clusterProfiler)
files <- getSampleFiles()
print(files)
peak <- readPeakFile(files[[5]])
peak
covplot(peak, weightCol="V5")
covplot(peak, weightCol="V5", chrs=c("2", "3"), xlim=c(4.5e6, 5e6))
## promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000)
## tagMatrix <- getTagMatrix(peak, windows=promoter)
##
## to speed up the compilation of this vignettes, we use a precalculated tagMatrix
promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000, by = "gene")
tagMatrix <- getTagMatrix(peak, windows=promoter)
tagMatrix <- getTagMatrix(peak, weightCol = NULL,windows = promoter)
tagMatrixList <- lapply(files, getTagMatrix, windows=promoter)
tagMatrix <- tagMatrixList[[5]]
tagHeatmap(tagMatrix, xlim=c(-3000, 3000), color="red")
peakHeatmap(files[[5]], TxDb=txdb, upstream=3000, downstream=3000, color="red")
plotAvgProf(tagMatrix, xlim=c(-3000, 3000),
            xlab="Genomic Region (5'->3')", ylab = "Read Count Frequency")
plotAvgProf2(files[[5]], TxDb=txdb, upstream=3000, downstream=3000,
             xlab="Genomic Region (5'->3')", ylab = "Read Count Frequency")
plotAvgProf(tagMatrix, xlim=c(-3000, 3000), conf = 0.95, resample = 3000)
library(org.At.tair.db)
peakAnno <- annotatePeak(files[[5]], tssRegion=c(-3000, 3000),
                         TxDb=txdb, annoDb="org.At.tair.db")
plotAnnoPie(peakAnno)
plotAnnoBar(peakAnno)
vennpie(peakAnno)
upsetplot(peakAnno)
upsetplot(peakAnno, vennpie=TRUE)
plotDistToTSS(peakAnno,
              title="Distribution of transcription factor-binding loci\nrelative to TSS")
library(ReactomePA)

pathway1 <- enrichPathway(as.data.frame(peakAnno)$geneId)
head(pathway1, 2)
gene <- seq2gene(peak, tssRegion = c(-1000, 1000), flankDistance = 3000, TxDb=txdb)
pathway2 <- enrichPathway(gene)
head(pathway2, 2)
dotplot(pathway2)plotAvgProf(tagMatrixList, xlim=c(-3000, 3000))
plotAvgProf(tagMatrixList, xlim=c(-3000, 3000), conf=0.95,resample=500, facet="row")
tagHeatmap(tagMatrixList, xlim=c(-3000, 3000), color=NULL)
peakAnnoList <- lapply(files, annotatePeak, TxDb=txdb,
                       tssRegion=c(-3000, 3000), verbose=FALSE)
plotAnnoBar(peakAnnoList)
plotDistToTSS(peakAnnoList)
genes = lapply(peakAnnoList, function(i) as.data.frame(i)$geneId)
names(genes) = sub("_", "\n", names(genes))
compKEGG <- compareCluster(geneCluster   = genes,
                           fun           = "enrichKEGG",
                           pvalueCutoff  = 0.05,
                           pAdjustMethod = "BH")
plot(compKEGG, showCategory = 15, title = "KEGG Pathway Enrichment Analysis")
genes= lapply(peakAnnoList, function(i) as.data.frame(i)$geneId)
vennplot(genes)
p <- GRanges(seqnames=c("chr1", "chr3"),
             ranges=IRanges(start=c(1, 100), end=c(50, 130)))
shuffle(p, TxDb=txdb)
enrichPeakOverlap(queryPeak     = files[[5]],
                  targetPeak    = unlist(files[1:4]),
                  TxDb          = txdb,
                  pAdjustMethod = "BH",
                  nShuffle      = 50,
                  chainFile     = NULL,
                  verbose       = FALSE)


-------------------
-------------------> files <- getSampleFiles()
> print(files)
$`GSM1906916_WT-H3K4me2vsInput.peaks.bed.gz`
[1] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ChIPseeker/extdata/GEO_sample_data/GSM1906916_WT-H3K4me2vsInput.peaks.bed.gz"

$`GSM1906917_WT-H3K4me3vsInput.peaks.bed.gz`
[1] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ChIPseeker/extdata/GEO_sample_data/GSM1906917_WT-H3K4me3vsInput.peaks.bed.gz"

$`GSM1906919_atx-H3K4me2vsInput.peaks.bed.gz`
[1] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ChIPseeker/extdata/GEO_sample_data/GSM1906919_atx-H3K4me2vsInput.peaks.bed.gz"

$`GSM1906920_atx-H3K4me3vsInput.peaks.bed.gz`
[1] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ChIPseeker/extdata/GEO_sample_data/GSM1906920_atx-H3K4me3vsInput.peaks.bed.gz"

$`GSM1906922_sdg2-H3K4me3vsInput.peaks.bed.gz`
[1] "/Library/Frameworks/R.framework/Versions/3.4/Resources/library/ChIPseeker/extdata/GEO_sample_data/GSM1906922_sdg2-H3K4me3vsInput.peaks.bed.gz"

> peak <- readPeakFile(files[[5]])
> peak
GRanges object with 15569 ranges and 2 metadata columns:
          seqnames               ranges strand |              V4        V5
             <Rle>            <IRanges>  <Rle> |        <factor> <numeric>
      [1]     chr1       [ 3589,  4098]      * |     MACS_peak_1    237.06
      [2]     chr1       [ 8314,  8808]      * |     MACS_peak_2    125.13
      [3]     chr1       [12484, 13025]      * |     MACS_peak_3    187.49
      [4]     chr1       [23134, 23807]      * |     MACS_peak_4    236.10
      [5]     chr1       [37304, 37697]      * |     MACS_peak_5    127.79
      ...      ...                  ...    ... .             ...       ...
  [15565]     chr5 [26957878, 26958401]      * | MACS_peak_15565    499.40
  [15566]     chr5 [26959898, 26960232]      * | MACS_peak_15566    107.73
  [15567]     chr5 [26962975, 26963673]      * | MACS_peak_15567    246.45
  [15568]     chr5 [26968829, 26969475]      * | MACS_peak_15568    457.56
  [15569]     chr5 [26969862, 26970715]      * | MACS_peak_15569    279.40
  -------
  seqinfo: 5 sequences from an unspecified genome; no seqlengths
> covplot(peak, weightCol="V4")
Error in .normarg_shift_or_weight(weight, "weight", x) : 
  'weight' must be a numeric vector, a single string, or a list-like object
> covplot(peak, weightCol="V5")
> covplot(peak, weightCol="V5", chrs=c("2", "3"), xlim=c(4.5e6, 5e6))
> ## promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000)
> ## tagMatrix <- getTagMatrix(peak, windows=promoter)
> ##
> ## to speed up the compilation of this vignettes, we use a precalculated tagMatrix
> promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000, by = "gene")
> tagMatrix <- getTagMatrix(peak, windows=promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> tagMatrix <- getTagMatrix(peak, weightCol = NULL,windows = promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> tagMatrixList <- lapply(files, getTagMatrix, windows=promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> tagMatrix <- tagMatrixList[[5]]
> tagHeatmap(tagMatrix, xlim=c(-3000, 3000), color="red")
> peakHeatmap(files[[5]], TxDb=txdb, upstream=3000, downstream=3000, color="red")
>> preparing promoter regions...	 2018-01-08 17:44:11 
>> preparing tag matrix...		 2018-01-08 17:44:11 
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> plotAvgProf(tagMatrix, xlim=c(-3000, 3000),
+             xlab="Genomic Region (5'->3')", ylab = "Read Count Frequency")
> plotAvgProf2(files[[5]], TxDb=txdb, upstream=3000, downstream=3000,
+              xlab="Genomic Region (5'->3')", ylab = "Read Count Frequency")
>> preparing promoter regions...	 2018-01-08 17:44:13 
>> preparing tag matrix...		 2018-01-08 17:44:13 
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> plotAvgProf(tagMatrix, xlim=c(-3000, 3000), conf = 0.95, resample = 3000)
>> Running bootstrapping for tag matrix...		 2018-01-08 18:16:07 
> library(org.At.tair.db)

> peakAnno <- annotatePeak(files[[5]], tssRegion=c(-3000, 3000),
+                          TxDb=txdb, annoDb="org.At.tair.db")
>> loading peak file...				 2018-01-08 18:16:18 
>> preparing features information...		 2018-01-08 18:16:18 
>> identifying nearest features...		 2018-01-08 18:16:19 
>> calculating distance from peak to TSS...	 2018-01-08 18:16:19 
>> assigning genomic annotation...		 2018-01-08 18:16:19 
Error in `[<-.data.frame`(`*tmp*`, tssIndex, "Promoter", value = TRUE) : 
  replacement has 1 row, data has 0
In addition: Warning messages:
1: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
2: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
3: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
4: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
5: In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> plotAnnoPie(peakAnno)
> plotAnnoBar(peakAnno)
> vennpie(peakAnno)
> upsetplot(peakAnno)
> upsetplot(peakAnno, vennpie=TRUE)
Error in gridPLT() : Figure region too small and/or viewport too large
> plotDistToTSS(peakAnno,
+               title="Distribution of transcription factor-binding loci\nrelative to TSS")
> library(ReactomePA)
ReactomePA v1.22.0  For help: https://guangchuangyu.github.io/ReactomePA

If you use ReactomePA in published research, please cite:
Guangchuang Yu, Qing-Yu He. ReactomePA: an R/Bioconductor package for reactome pathway analysis and visualization. Molecular BioSystems 2016, 12(2):477-479
> pathway1 <- enrichPathway(as.data.frame(peakAnno)$geneId)
Loading required package: org.Hs.eg.db



I try to replace the sample data in your package with my data, my data are from Arabidopsis.
But the results suggested lot of errors, may be the annotation library of I used is not work.

**Comment by sunxuwu** [comment]
I have replaced the sample data in your package with my own data that come from Arabidopsis. 

There are many error massages in Console windows. I don't know how to solve them. Could you please give me a solution?
> tagMatrix <- getTagMatrix(peak, windows=promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> tagMatrix <- getTagMatrix(peak, weightCol = NULL,windows = promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> tagMatrixList <- lapply(files, getTagMatrix, windows=promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)

**Comment by GuangchuangYu** [comment]
### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))

**Comment by sunxuwu** [comment]
## loading packages
library(ChIPseeker)
library(TxDb.Athaliana.BioMart.plantsmart22)
txdb <- TxDb.Athaliana.BioMart.plantsmart22
library(clusterProfiler)
files <- getSampleFiles()
print(files)
peak <- readPeakFile(files[[5]])
peak
covplot(peak, weightCol="V5")
covplot(peak, weightCol="V5", chrs=c("chr2", "chr3"), xlim=c(4.5e6, 5e6))
promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000, by = "gene")
tagMatrix <- getTagMatrix(peak, windows=promoter)
tagMatrixList <- lapply(files, getTagMatrix, windows=promoter)
tagMatrix <- tagMatrixList[[5]]
tagHeatmap(tagMatrix, xlim=c(-3000, 3000), color="red")
peakHeatmap(files[[5]], TxDb=txdb, upstream=3000, downstream=3000, color="red")
plotAvgProf(tagMatrix, xlim=c(-3000, 3000),
            xlab="Genomic Region (5'->3')", ylab = "Read Count Frequency")
plotAvgProf2(files[[5]], TxDb=txdb, upstream=3000, downstream=3000,
             xlab="Genomic Region (5'->3')", ylab = "Read Count Frequency")
plotAvgProf(tagMatrix, xlim=c(-3000, 3000), conf = 0.95, resample = 3000)
library(org.At.tair.db)
peakAnno <- annotatePeak(files[[5]], tssRegion=c(-3000, 3000),
                         TxDb=txdb, annoDb="org.At.tair.db")
plotAnnoPie(peakAnno)
plotAnnoBar(peakAnno)
vennpie(peakAnno)
upsetplot(peakAnno)
upsetplot(peakAnno, vennpie=TRUE)
plotDistToTSS(peakAnno,
              title="Distribution of transcription factor-binding loci\nrelative to TSS")
library(ReactomePA)

pathway1 <- enrichPathway(as.data.frame(peakAnno)$geneId)
head(pathway1, 2)
gene <- seq2gene(peak, tssRegion = c(-1000, 1000), flankDistance = 3000, TxDb=txdb)
pathway2 <- enrichPathway(gene)
head(pathway2, 2)
dotplot(pathway2)

==========================================

in console windows

=============================> peak <- readPeakFile(files[[5]])
> peak
GRanges object with 15569 ranges and 2 metadata columns:
          seqnames               ranges strand |              V4        V5
             <Rle>            <IRanges>  <Rle> |        <factor> <numeric>
      [1]     chr1       [ 3589,  4098]      * |     MACS_peak_1    237.06
      [2]     chr1       [ 8314,  8808]      * |     MACS_peak_2    125.13
      [3]     chr1       [12484, 13025]      * |     MACS_peak_3    187.49
      [4]     chr1       [23134, 23807]      * |     MACS_peak_4    236.10
      [5]     chr1       [37304, 37697]      * |     MACS_peak_5    127.79
      ...      ...                  ...    ... .             ...       ...
  [15565]     chr5 [26957878, 26958401]      * | MACS_peak_15565    499.40
  [15566]     chr5 [26959898, 26960232]      * | MACS_peak_15566    107.73
  [15567]     chr5 [26962975, 26963673]      * | MACS_peak_15567    246.45
  [15568]     chr5 [26968829, 26969475]      * | MACS_peak_15568    457.56
  [15569]     chr5 [26969862, 26970715]      * | MACS_peak_15569    279.40
  -------
  seqinfo: 5 sequences from an unspecified genome; no seqlengths> promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000, by = "gene")
> tagMatrix <- getTagMatrix(peak, windows=promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> tagMatrix <- getTagMatrix(peak, weightCol = NULL,windows = promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> tagMatrixList <- lapply(files, getTagMatrix, windows=promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)

I have replaced the sample data in your package with my data from Arabidopsis. But results in many errors.
Could you please give me a solution? Thank you very much!
