### ISSUE TITLE
How to make ChIPseeker work for Arabidopsis

### ISSUE THREAD

**Issue by sunxuwu** [GuangchuangYu/ChIPseeker#68]
I have replaced the sample data in your package with my own data that come from Arabidopsis.

There are many error massages in Console windows. I don't know how to solve them. Could you please give me a solution?

tagMatrix <- getTagMatrix(peak, windows=promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) :
group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
The 2 combined objects have no sequence levels in common. (Use
suppressWarnings() to suppress this warning.)
tagMatrix <- getTagMatrix(peak, weightCol = NULL,windows = promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) :
group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
The 2 combined objects have no sequence levels in common. (Use
suppressWarnings() to suppress this warning.)
tagMatrixList <- lapply(files, getTagMatrix, windows=promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) :
group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
The 2 combined objects have no sequence levels in common. (Use
suppressWarnings() to suppress this warning.)

**Comment by GuangchuangYu** [comment]
duplicated, <https://github.com/GuangchuangYu/ChIPseeker/issues/67#issuecomment-355937404>.
