### ISSUE TITLE
Error in sqliteSendQuery

### ISSUE THREAD

**Issue by PFRoux** [GuangchuangYu/ChIPseeker#7]
Dear Guangchuang,

I am having issues running ChIPseeker annotatePeak command. 

The error message I get is :
> annotatePeak(Ann_K4Me1_DB_UP_TSS, TxDb=TxDb)
Error in unlist(metadata(TXDB)) : 
  erreur d'évaluation de l'argument 'x' lors de la sélection d'une méthode pour la fonction 'unlist' : Error in sqliteSendQuery(con, statement, bind.data) : 
  expired SQLiteConnection

In this example, I'm running the analysis using a custom TxDb object I created using biomaRt.
But I have the same error when trying to run annotatePeak on the example data set included in your package.

I think I need to deal with the installation of SQLite package - which seems to work properly til now.
But, I would like to know if you already faced such an error and have suggetions.

Many thanks for your help,

Pierre-François

**Comment by GuangchuangYu** [comment]
I don't faced that error before. It should be caused by AnnotationDbi.

**Comment by PFRoux** [comment]
Thx for your answer.
I will try to reinstall AnnotationDbi and DBI as well.

**Comment by GuangchuangYu** [comment]
FYI, see [https://support.bioconductor.org/p/66576/#70476](https://support.bioconductor.org/p/66576/#70476).
