### ISSUE TITLE
Error: package or namespace load failed for ‘ChIPseeker’

### ISSUE THREAD

**Issue by kehuachen** [GuangchuangYu/ChIPseeker#78]
Y叔你好，新手想使用chipeeker包试着处理一下数据，但是无法载入，错误如下：
Error: package or namespace load failed for ‘ChIPseeker’:
 'namespace:DOSE'没有出口‘upsetplot’这个对象
之前因为要分析rnaseq将以下几个包做了升级：
clusterprofiler  3.7.1
DOSE  3.5
enrichplot 0.99.12
是不是使用了development version的原因，但是我将DOSE降版本后依旧得不到解决，问题出在哪里？

**Comment by GuangchuangYu** [comment]
<https://github.com/GuangchuangYu/clusterProfiler/issues/132>
