### ISSUE TITLE
Error in getGenomicAnnoStat(peak.gr) : object 'plab' not found

### ISSUE THREAD

**Issue by kehuachen** [GuangchuangYu/ChIPseeker#79]
when I try to run annopeak() , I get this error:
Error in getGenomicAnnoStat(peak.gr) : object 'plab' not found.
ChIPseeker package is github version and every supporting packages are up to date, I don't know what went wrong.
is this a bug?

+ [ ] Have you read [Feedback](https://guangchuangyu.github.io/chipseeker/#feedback) and follow the [guide](https://guangchuangyu.github.io/2016/07/how-to-bug-author/)?
	* [ ] make sure your are using the latest release version
	* [ ] read the [documents](https://guangchuangyu.github.io/chipseeker/documentation/)
	* [ ] google your quesion/issue

### Describe you issue

* [ ] Make a reproducible example (*e.g.* [1](https://gist.github.com/talonsensei/e1fad082657054207f249ec98f0920eb))
* [ ] your code should contain comments to describe the problem (*e.g.* what expected and actually happened?)

### Ask in right place

* [ ] for bugs or feature requests, post here (github issue)
* [ ] for questions, please post to [Bioconductor](https://support.bioconductor.org/) or [Biostars](https://www.biostars.org/) with tag `ChIPseeker`

**Comment by GuangchuangYu** [comment]
duplicated, <https://support.bioconductor.org/p/107764/#107830>.
