### ISSUE TITLE
annotatePeak should find more reasonable result and Regulate line width when using  plotAvgProf()

### ISSUE THREAD

**Issue by sunnyfanyy** [GuangchuangYu/ChIPseeker#82]
Hi, Doctor Yu. I have some questions when using 'ChIPseeker' package.
Here are my postscripts:
```R
library(ChIPseeker)
#packageVersion("ChIPseeker")
#[1] ‘1.16.0’
library(TxDb.Athaliana.BioMart.plantsmart28)
library(BSgenome.Athaliana.TAIR.TAIR9)

seqlevelsStyle(TxDb.Athaliana.BioMart.plantsmart28) <- seqlevelsStyle(BSgenome.Athaliana.TAIR.TAIR9)
txdb <- TxDb.Athaliana.BioMart.plantsmart28

peak <- GRanges(seqnames = "Chr1", ranges = IRanges(4230080,4230224))
ap <- annotatePeak(peak, tssRegion=c(-1500, 500), overlap = "TSS", TxDb=txdb,
                              addFlankGeneInfo=T, flankDistance=1500)
as.GRanges(ap)

> as.GRanges(ap)
GRanges object with 1 range and 12 metadata columns:
      seqnames          ranges strand |        annotation   geneChr geneStart   geneEnd
         <Rle>       <IRanges>  <Rle> |       <character> <integer> <integer> <integer>
  [1]     Chr1 4230080-4230224      * | Downstream (<1kb)         1   4231027   4231146
      geneLength geneStrand      geneId transcriptId distanceToTSS             flank_txIds
       <integer>  <integer> <character>  <character>     <numeric>             <character>
  [1]        120          2   AT1G12423  AT1G12423.1           922 AT1G12420.1;AT1G12423.1
            flank_geneIds flank_gene_distances
              <character>          <character>
  [1] AT1G12420;AT1G12423             -942;922
  -------
  seqinfo: 1 sequence from an unspecified genome

```
As you can see, the peak was assigned to **Downstream of AT1G12423**, while it was also located in the **Promoter of AT1G12420**.   
 The annotation of peak associated genes by 'ChIPseeker 1.16.0' is to identify the neareast gene of the peak.  While, the more reasonable result is to identify the gene which the peak assigned to its promoter.

By the way, one peak can also located in the **bidirectional promoters**, which means there are two adjacent genes transcribed on opposite directions.  It is better to annotate this kind of peak to both genes.

At last,  I cannot find how to regulate the **line width** when using **plotAvgProf()**.

Thanks again for your perfect package! ^_^

**Comment by GuangchuangYu** [comment]
`Downstream of AT1G12423` is correct as 922 (`distanceToTSS`) is larger than your promoter setting (`tssRegion=c(-1500, 500)`).

for `bidirectional promoters`, the `addFlankGeneInfo` can give you such information, although not directly.

for `line width`, `+aes(size=I(Line_Width_Value)` is what you looking for.
