### ISSUE TITLE
I can't get the tagMatrix, it is still wrong.

### ISSUE THREAD

**Issue by jailynai** [GuangchuangYu/ChIPseeker#86]
follow the code:
F <- readPeakFile("/Users/jail/Desktop/Galaxy181.bed")
print(F1)
F_peak <- readPeakFile(F[[4]])
F_peakAnno <-annotatePeak(F1,tssRegion = c(-2500,2499),
TxDb = "TxDb.Athaliana.BioMart.plantsmart28", 
annoDb = "org.At.tair.db")
covplot(F, weightCol="V5")
txdb <- TxDb.Athaliana.BioMart.plantsmart28
promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000)
tagMatrix <- getTagMatrix(F1, windows=promoter)
报错：
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
The 2 combined objects have no sequence levels in common. (Use
suppressWarnings() to suppress this warning.)

**Comment by GuangchuangYu** [comment]
it seems something like <https://github.com/GuangchuangYu/ChIPseeker/issues/30>.

**Comment by jailynai** [comment]
it can't work. I can get the data.
> print(F)
GRanges object with 4706 ranges and 7 metadata columns:
         seqnames        ranges strand |              V4        V5       V6        V7
            <Rle>     <IRanges>  <Rle> |        <factor> <integer> <factor> <numeric>
     [1]     chr1   20762-21095      * |    MACS2_peak_1        54        .   2.52941
     [2]     chr1   38010-38230      * |    MACS2_peak_2        44        .      2.12
     [3]     chr1   46578-46987      * |    MACS2_peak_3        44        .   2.51163
     [4]     chr1   51096-51517      * |    MACS2_peak_4        41        .   2.39637
     [5]     chr1   56712-57347      * |    MACS2_peak_5        92        .   3.25936
     ...      ...           ...    ... .             ...       ...      ...       ...
  [4702]     chrC   55954-76108      * | MACS2_peak_4702        94        .   1.46442
  [4703]     chrC   76371-84119      * | MACS2_peak_4703       139        .   1.59087
  [4704]     chrC 110314-114085      * | MACS2_peak_4704       148        .   1.61942
  [4705]     chrC 114284-125924      * | MACS2_peak_4705       102        .   1.48414
  [4706]     chrC 126017-128194      * | MACS2_peak_4706        96        .   1.47328
                V8        V9       V10
         <numeric> <numeric> <integer>
     [1]   7.75937    5.4387       175
     [2]   6.65219   4.48508        22
     [3]   6.67265   4.48508       228
     [4]   6.30223   4.17276       299
     [5]   12.0954   9.28048       342
     ...       ...       ...       ...
  [4702]  12.33263   9.47648     16244
  [4703]  17.21898  13.91292      5515
  [4704]  18.20124  14.81484      2637
  [4705]  13.14417  10.21581      7562
  [4706]  12.52234   9.65809       791

**Comment by GuangchuangYu** [comment]
If you really read the link I posted, you should also check the seqnames of TxDb.

**Comment by jailynai** [comment]
hi I still can't get the plot, the code followed:> library("org.At.tair.db")> library("TxDb.Athaliana.BioMart.plantsmart28")> library("VennDiagram")Loading required package: futile.logger> library("clusterProfiler")> txdb <- TxDb.Athaliana.BioMart.plantsmart28> FHY1 <- readPeakFile("/Users/jailynhan/Desktop/Galaxy181-[SUMO_HS].bed")> print(FHY1)GRanges object with 4706 ranges and 7 metadata columns:         seqnames        ranges strand |              V4        V5       V6        V7            <Rle>     <IRanges>  <Rle> |        <factor> <integer> <factor> <numeric>     [1]     chr1   20762-21095      * |    MACS2_peak_1        54        .   2.52941     [2]     chr1   38010-38230      * |    MACS2_peak_2        44        .      2.12     [3]     chr1   46578-46987      * |    MACS2_peak_3        44        .   2.51163     [4]     chr1   51096-51517      * |    MACS2_peak_4        41        .   2.39637     [5]     chr1   56712-57347      * |    MACS2_peak_5        92        .   3.25936     ...      ...           ...    ... .             ...       ...      ...       ...  [4702]     chrC   55954-76108      * | MACS2_peak_4702        94        .   1.46442  [4703]     chrC   76371-84119      * | MACS2_peak_4703       139        .   1.59087  [4704]     chrC 110314-114085      * | MACS2_peak_4704       148        .   1.61942  [4705]     chrC 114284-125924      * | MACS2_peak_4705       102        .   1.48414  [4706]     chrC 126017-128194      * | MACS2_peak_4706        96        .   1.47328                V8        V9       V10         <numeric> <numeric> <integer>     [1]   7.75937    5.4387       175     [2]   6.65219   4.48508        22     [3]   6.67265   4.48508       228     [4]   6.30223   4.17276       299     [5]   12.0954   9.28048       342     ...       ...       ...       ...  [4702]  12.33263   9.47648     16244  [4703]  17.21898  13.91292      5515  [4704]  18.20124  14.81484      2637  [4705]  13.14417  10.21581      7562  [4706]  12.52234   9.65809       791  -------  seqinfo: 6 sequences from an unspecified genome; no seqlengths> FHY1_peakAnno <-annotatePeak(FHY1,tssRegion = c(-2000,2000),+                              TxDb = "TxDb.Athaliana.BioMart.plantsmart28", +                              annoDb = "org.At.tair.db")>> preparing features information...  2018-09-22 14:24:20 Error in (function (classes, fdef, mtable)  :   unable to find an inherited method for function 'transcriptsBy' for signature '"character"' 

    On Thursday, September 20, 2018 5:15 PM, Guangchuang Yu <notifications@github.com> wrote:
 

 If you really read the link I posted, you should also check the seqnames of TxDb.—

**Comment by jailynai** [comment]
it is work. i am so sorry.
thanks for your helping
