### ISSUE TITLE
Limit distance for enrichAnnoOverlap

### ISSUE THREAD

**Issue by riederd** [GuangchuangYu/ChIPseeker#9]
enrichAnnoOverlap uses the common nearest gene of two peaks as overlap measure, but the distance of the two peaks and/or the the distance to the TSS of the common nearest gene can be large e.g. several 10kb. Therefore it would be great to be able to specify a maximum distance between pairs of peaks and optionally a maximum distance of pairs of peaks and the TSS.

**Comment by GuangchuangYu** [comment]
It's a neat idea to restrict the annotation not only for `enrichAnnoOverlap` but also in functional enrichment analysis of nearest gene annotation.

I create a function, `dropAnno`, that restrict the result by specifying `distanceToTSS_cutoff` value. 

see https://github.com/GuangchuangYu/ChIPseeker/commit/3548bc9977d42c8df3827594857c10057a6da433

**Comment by riederd** [comment]
Is it already used in enrichAnnoOveralp, I couldn't find the commit?

**Comment by GuangchuangYu** [comment]
see https://github.com/GuangchuangYu/ChIPseeker/commit/10c544ef52db3fd69c4e7a3251549aca3aec46b6
