### ISSUE TITLE
having porblem Tagmatrix generation

### ISSUE THREAD

**Issue by saumya2sarkar2** [GuangchuangYu/ChIPseeker#90]
```
> txdb <-TxDb.Rnorvegicus.UCSC.rn6.refGene
> h3k4<-"/home/sandeep/Desktop/Saumya/Chip 1st exp/H3K4_Input_summits.bed"
> h3k4rpf<-readPeakFile(h3k4)
> covplot(h3k4rpf,weightCol="V5")
> promoter <- getPromoters(TxDb=txdb, upstream=3000, downstream=3000)
> h3k4.tagMatrix <- getTagMatrix(h3k4rpf, windows=promoter)
Error in split.default(1:length(windows), as.factor(seqnames(windows))) : 
  group length is 0 but data length > 0
In addition: Warning message:
In .Seqinfo.mergexy(x, y) :
  The 2 combined objects have no sequence levels in common. (Use
  suppressWarnings() to suppress this warning.)
> tagHeatmap(h3k4.tagMatrix, xlim=c(-3000, 3000), color="red")
Error in is(tagMatrix, "list") : object 'h3k4.tagMatrix' not found
```

**Comment by saumya2sarkar2** [comment]
[H3K4_Input_summits (copy).bed.tar.gz](https://github.com/GuangchuangYu/ChIPseeker/files/2656478/H3K4_Input_summits.copy.bed.tar.gz)
[H3K4_Input_summits (copy).bed.tar.gz](https://github.com/GuangchuangYu/ChIPseeker/files/2656480/H3K4_Input_summits.copy.bed.tar.gz)

**Comment by saumya2sarkar2** [comment]
[H3K4_Input_summits .bed.tar.gz](https://github.com/GuangchuangYu/ChIPseeker/files/2656483/H3K4_Input_summits.bed.tar.gz)

**Comment by GuangchuangYu** [comment]
if you really follow <https://github.com/GuangchuangYu/ChIPseeker/issues/66#issuecomment-353224034>.

![image](https://user-images.githubusercontent.com/626539/49844017-3524f300-fdfc-11e8-8dbd-e690e1202233.png)
