### ISSUE TITLE
Set the TSS label in "plotAvgProf" to a parameter to provide for the function

### ISSUE THREAD

**Issue by mcamarad** [GuangchuangYu/ChIPseeker#91]
Hi,

Thank you for this amazing package! I was wondering if it was possible to change the TSS label to a parameter to be provided when calling plotAvgProf function. I managed to use plotAvgProf around other things that are not TSS and it is pretty misleading having that label there. That also would help to make the function more general.

Thank you so much in advance!

**Comment by GuangchuangYu** [comment]
added in dev branch, see <https://github.com/GuangchuangYu/ChIPseeker/commit/18e058f645592b3cccd24419b5c2f1b414ddeb43>.

**Comment by GuangchuangYu** [comment]
with v >= 1.9.1, you can pass `origin_label = "what ever you want"`.
